spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: 
    password: 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    
server:
  port: 8095
